openapi: 3.0.3
info:
  title: Mock Bot API
  version: '1.0'
  description: Lightweight component used to demonstrate chatbot integration with a Distributed Message Room.
  license:
    name: MIT-0
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000'
paths:
  /client-api/chats:
    post:
      summary: Create chat
      operationId: post-chats
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                title: Chat
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: a51d61c3-ce60-478d-98d5-21b8b99271ae
                    readOnly: true
                  messages:
                    type: array
                    items:
                      title: Message
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          readOnly: true
                        content:
                          type: string
                          example: 'Hi, I need to update my drivers licence.'
                        createdAt:
                          type: string
                          format: date-time
                          example: '2022-05-13T11:28:29.972Z'
                          readOnly: true
                      required:
                        - id
                        - content
                        - createdAt
                  createdAt:
                    type: string
                    format: date-time
                    example: '2022-05-13T11:28:29.972Z'
                    readOnly: true
                required:
                  - id
                  - createdAt
              examples: {}
      description: Start a new chat.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value: {}
    parameters: []
  '/client-api/chats/{chatId}/messages':
    parameters:
      - schema:
          type: string
          format: uuid
          example: 5675d57d-f516-4c5c-9307-8de5565d924b
        name: chatId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-chats-chatId-messages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Message
                  x-stoplight:
                    id: 8rb81u2ztllz0
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      readOnly: true
                    content:
                      type: string
                      example: 'Hi, I need to update my drivers licence.'
                    createdAt:
                      type: string
                      format: date-time
                      example: '2022-05-13T11:28:29.972Z'
                      readOnly: true
                  required:
                    - id
                    - content
                    - createdAt
      description: ''
    post:
      summary: ''
      operationId: post-chats-chatId-messages
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                title: Message
                x-stoplight:
                  id: 8rb81u2ztllz0
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  content:
                    type: string
                    example: 'Hi, I need to update my drivers licence.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2022-05-13T11:28:29.972Z'
                    readOnly: true
                required:
                  - id
                  - content
                  - createdAt
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              title: Message
              x-stoplight:
                id: 8rb81u2ztllz0
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  readOnly: true
                content:
                  type: string
                  example: 'Hi, I need to update my drivers licence.'
                createdAt:
                  type: string
                  format: date-time
                  example: '2022-05-13T11:28:29.972Z'
                  readOnly: true
              required:
                - id
                - content
                - createdAt
  /dmr-api/messages:
    parameters: []
    post:
      summary: ''
      operationId: post-dmr-api-messages
      responses:
        '202':
          description: Accepted
      description: Receive message from DMR.
      parameters:
        - name: X-Sent-From
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: b4ac37cf-1ae9-429e-9d05-22d7db901ef3
          description: Uuid of the participant that sent the message.
        - name: X-Message-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: bb20ba03-5e52-4a61-bcc1-0ad538f1b448
          description: 'Uuid generated by the sender of a message for correlating async responses to a specific request. '
        - name: X-Message-Id-Ref
          in: header
          schema:
            type: string
            format: uuid
            example: 545226ad-0b8d-4ccb-b83f-6b3ad8d44ec8
          description: Reference to the original X-Message-Id we are replying to.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
          application/json:
            schema:
              title: ClassificationResponse
              type: object
              description: ''
              properties:
                messages:
                  type: array
                  items:
                    type: string
                classification:
                  type: string
              required:
                - messages
                - classification
        description: Encrypted payload
components:
  schemas:
    Chat:
      title: Chat
      x-stoplight:
        id: 0wi8ep6tujz0u
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: a51d61c3-ce60-478d-98d5-21b8b99271ae
          readOnly: true
        messages:
          type: array
          items:
            title: Message
            x-stoplight:
              id: 8rb81u2ztllz0
            type: object
            properties:
              id:
                type: string
                format: uuid
                readOnly: true
              content:
                type: string
                example: 'Hi, I need to update my drivers licence.'
              createdAt:
                type: string
                format: date-time
                example: '2022-05-13T11:28:29.972Z'
                readOnly: true
            required:
              - id
              - content
              - createdAt
        createdAt:
          type: string
          format: date-time
          example: '2022-05-13T11:28:29.972Z'
          readOnly: true
      required:
        - id
        - createdAt
    Message:
      title: Message
      x-stoplight:
        id: 8rb81u2ztllz0
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        content:
          type: string
          example: 'Hi, I need to update my drivers licence.'
        createdAt:
          type: string
          format: date-time
          example: '2022-05-13T11:28:29.972Z'
          readOnly: true
      required:
        - id
        - content
        - createdAt
  requestBodies: {}
  responses: {}
  securitySchemes: {}
